### ISSUE TITLE
[Task] 메인 페이지 구현

### ISSUE THREAD

**Issue by LEEJAESHIN** [codestates/CodeCooperation#1]
### ISSUE
- Group: client
- Type: feature
- Detail: 메인 페이지 구현

### TODO
 - [ ] 메인화면 레이아웃 형식 잡기
 - [ ] 일러스트를 활용해 UI만들기
 - [ ] 버튼 기능을 적절히 활용

### Labels
- Estimated time: E: 6h
- Group : client
- Sprint: Sprint__1__
- Urgency: Middle
