### ISSUE TITLE
[Task]  네비게이터,Footer 컴포넌트 구현

### ISSUE THREAD

**Issue by LEEJAESHIN** [codestates/CodeCooperation#3]
### ISSUE
- Group: client
- Type: feature
- Detail: 

### TODO
 - [x] 상단 레이아웃 잡기
 - [x] 버튼 텍스트 와 링크 잘 연결하기
 - [x] 화면 밑 푸터 기능 구현

### Labels
- Estimated time: E: 1h
- Group : client
- Sprint: Sprint__1__
- Urgency: Low
