### ISSUE TITLE
[Task] 마이 페이지 구현

### ISSUE THREAD

**Issue by LEEJAESHIN** [codestates/CodeCooperation#4]
### ISSUE
- Group: Client
- Type: feature
- Detail: fix actions from client redux

### TODO
 - [ ] 마이페이지 레이아웃 구축
 - [ ] 마이페이지 유저정보 구현 (State에서 가져올수 있어야함)
 - [ ] 유저 상세페이지 기능 구현(Advanced?)

### Labels
- Estimated time: E: 6h
- Group : client
- Sprint: Sprint__2__
- Urgency: Middle
