### ISSUE TITLE
[Task] 게시글 작성 페이지 구현

### ISSUE THREAD

**Issue by LEEJAESHIN** [codestates/CodeCooperation#5]
### ISSUE
- Group: client,
- Type: feature
- Detail: 

### TODO
 - [x] 게시글작성 레이아웃 작성
 - [ ] 스택 스크롤 구현 (누를시 input에 반영 될수 있도록)
 - [ ] 정보 미입력시 오류코드 작성
 - [ ] 정보를 axios 요청코드 작성

### Labels
- Estimated time: E: 3h
- Group : client
- Sprint: Sprint__1__
- Urgency: Middle
