### ISSUE TITLE
[Task] 게시글 상세 페이지 구현

### ISSUE THREAD

**Issue by LEEJAESHIN** [codestates/CodeCooperation#6]
### ISSUE
- Group: client
- Type: feature
- Detail: 상세페이지 안에 지원신청 모달창도 구현해야 함

### TODO
 - [x] 상세페이지 레이아웃 구현
 - [ ] 지원신청 기능 구현 (누를시 모달창 및 정보 전송)
 - [ ] 북마크 기능 구현

### Labels
- Estimated time: E: 6h
- Group : client
- Sprint: Sprint__2__
- Urgency: Middle
