### ISSUE TITLE
[Task] 게시글 페이지 구현

### ISSUE THREAD

**Issue by LEEJAESHIN** [codestates/CodeCooperation#7]
### ISSUE
- Group: client
- Type: feature
- Detail: SubNavbar 구현 해야 함

### TODO
 - [ ] 게시글 페이지, SubNavbar  레이아웃 구현
 - [ ] 데이터 만큼 게시물이 생성 될수 있도록 구현
 - [ ] Search 기능 구현 (Advanced)

### Labels
- Estimated time: E: 9h
- Group : client
- Sprint: Sprint__3__
- Urgency: Middle
